version: "3"
services:
        sonarqube:      
                image: sonarqube:8.9.0-community
                container_name: mysonarqube
                depends_on:
                        - db
                environment:
                        SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
                        SONAR_JDBC_USERNAME: sonar
                        SONAR_JDBC_PASSWORD: sonaradmin
                restart: always
                volumes:
                        - sc_data:/opt/sonarqube/data
                        - sc_extensions:/opt/sonarqube/extensions
                        - sc_logs:/opt/sonarqube/logs
                ports:
                        - 9000:9000
                networks: 
                        - dockerNet


        db:               
                image: postgres 
                container_name: mypostgres
                environment: 
                        POSTGRES_USER: sonar
                        POSTGRES_PASSWORD: sonaradmin
                        POSTGRES_USER: sonar
                restart: always
                volumes:
                        - db_data:/var/lib/postgresql/data
                networks:
                        - dockerNet          


        jenkins:
                image: jenkins:2.60.3
                container_name: myjenkins
                restart: always
                volumes: 
                        - jenkins_data:/var/jekins_home
                ports:
                        - 8080:8089
                        - 50000:50000
                networks:
                        - dockerNet


        nexus3:
                image: sonatype/nexus3
                container_name: mynexus3
                restart: always
                volumes:
                        - nexus_data:/nexus_data
                networks:
                        - dockerNet
                ports:
                        - 8081:8088
                  
        myjavaapi:
                image: myjavaapi:latest
                build:
                        context: .
                        dockerfile: multistage.Dokerfile
                ports:
                        - 9009:8080
                networks:
                        - apinet

volumes:                

        sc_data:        
        sc_extensions:
        sc_logs:
        db_data:        
        jenkins_data:
        nexus_data:
networks:
        dockerNet:
        apinet: 
